const express = require('express');
const app = express();
const router = express.Router();
const lnClient = require("../lightning-client/client").Client;
const utils = require("../utils");

/**
 * POST /getinvoice will generate an invoice
 * on the LND Node.
 */
router.post("/", async (_, res) => {

// Request an invoice to be generated by the lnd node. 
  let invoiceAmt = {value: 100}

  lnClient.AddInvoice(invoiceAmt, (err, invoiceRes) => {  
  // Check for returned err.
  if (err) {
    res.render('invoice', {invoice: "There was an error: " + err});
      return;
  };

  // Parse the invoice as JSON and retrieve the payment_request.
  let invoiceObj = utils.objToJSON(invoiceRes);
  let payReq = invoiceObj["payment_request"];

  // Render invoice.html passing the payment request.
  res.render('invoice', {invoice: payReq});
  return;
  });

});

module.exports = router;
